###Solving linear alegra equations
See numpy link for more help
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html


In [8]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

Solving this sort of equation:

$A \overrightarrow{x} = \overrightarrow{b}$

where $A$ is a matrix.

For example:

$A= \begin{pmatrix}
3 & 1\\ 
1 & 2
\end{pmatrix}$

$\overrightarrow{x} = \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

$\overrightarrow{b} = \begin{pmatrix}
b_1\\ 
b_2
\end{pmatrix}$

represents the set of equations:

$ 3 x_1 + x_2 = 9$

$ x_1 + 2 x_2 = 8$

Solving this example: 

Define the matrix $A$, define $\overrightarrow{b}$, then solve for $\overrightarrow{x}$

In [19]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([ 2.,  3.])

Evaluating the results:

This means that
$\overrightarrow{x} = \begin{pmatrix}
2\\ 
3
\end{pmatrix}$

or in other words:

$ x_1 = 2$

and

$ x_2 = 3$

Let's try applying this to a problem in circuits -- problem 11 from Ch. 1 of Eggleston "Basic Electronics". By applying Kirchoff's voltage loop to the circuit in this problem (and possibly junction rule), we create three equations that relate the three currents $I_1$, $I_2$, and $I_3$. The vector $\overrightarrow{x}$ is meaning 

$\overrightarrow{x} = \begin{pmatrix}
I_1\\ 
I_2\\
I_3
\end{pmatrix}$

In [20]:
a = np.array([[1,-1,1], [-3,-5,0], [0,5,8]])
b = np.array([0,-5,15])
x = np.linalg.solve(a, b)
x

array([-0.12658228,  1.07594937,  1.20253165])

In this example, we can check to see if $I_1 + $I_3 = I_2$: 

In [26]:
-0.12658228 +  1.20253165

1.07594937

Looks correct.

Practice ways of printing a matrix:

In [27]:
print(np.matrix(a))

[[ 1 -1  1]
 [ 3  0  8]
 [ 3  5  0]]


In [28]:
a

array([[ 1, -1,  1],
       [ 3,  0,  8],
       [ 3,  5,  0]])

Another example:

In [29]:
a = np.array([[1,-1,1], [3,0,8], [3,5,0]])
b = np.array([0,10,-5])
x = np.linalg.solve(a, b)
x

array([-1.83673469,  0.10204082,  1.93877551])

In [25]:
-1.83673469+1.93877551

0.10204082000000003