###Solving linear alegra equations
See numpy link for more help
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html


In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [8]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([ 2.,  3.])

In [12]:
a = np.array([[1,-1,1], [3,0,8], [3,5,0]])
b = np.array([0,10,-5])
x = np.linalg.solve(a, b)
x

array([-1.83673469,  0.10204082,  1.93877551])

In [13]:
-1.83673469+1.93877551

0.10204082000000003

works!
this was problem 11 from ch. 1 of eggleston "Basic Electronics"

In [17]:
a = np.array([[1,-1,1], [-3,-5,0], [0,5,8]])
b = np.array([0,-5,15])
x = np.linalg.solve(a, b)
x

array([-0.12658228,  1.07594937,  1.20253165])

In [19]:
-0.12658228 +  1.20253165

1.07594937

In [14]:
print(np.matrix(a))

[[ 1 -1  1]
 [ 3  0  8]
 [ 3  5  0]]


In [16]:
a

array([[ 1, -1,  1],
       [ 3,  0,  8],
       [ 3,  5,  0]])